services:
  notebook:
      build:
        context: ./dockerimg
        dockerfile: ./Dockerfile
        args:
          user_id: ${UID}
      environment:
        - JUPYTER_TOKEN=${PASSWORD}
      volumes:
        - ./jupyter_volume:/home/jovyan/work
      ports:
        - ${PORT}:8888
      expose:
        - ${PORT}
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "8001:8001" # Redis Insights
    deploy:
      replicas: 1
